comment: false

codecov:
  notify:
    # If this number is greater than the number of reports to be submitted,
    # then `codecov/project` and `codecov/patch` checks will not be reflected
    # among the other checks. Since this number is greater than the number of
    # reports sent from the master branch, we will no longer see codecov checks on it.
    after_n_builds: 55
