name: "Install environment using Mamba"
description: "Prepare the environment to run Modin"
inputs:
  python-version:
    description: "Python version to install"
    default: "3.9"
  environment-file:
    description: "Conda environment yml"
    required: true
  activate-environment:
    description: "Conda environment to activate"
    default: "modin"

runs:
  using: "composite"
  steps:
    - name: Get current week
      id: get-week
      # use current week as cache key to periodically refresh the cache,
      # as cache is based on requirements, but dependencies push
      # updated versions at some irregular pace
      run: echo "thisweek=$(/bin/date -u '+%Y.w%W')" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache conda
      id: cache-conda
      uses: actions/cache@v4
      with:
        path: |
          ~/conda_pkgs_dir
          ~/.cache/pip
        key:
          ${{ runner.os }}-conda-${{ steps.get-week.outputs.thisweek }}-${{ hashFiles(inputs.environment-file) }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        activate-environment: ${{ inputs.activate-environment }}
        environment-file: ${{ inputs.environment-file }}
        python-version: ${{ inputs.python-version }}
        channel-priority: strict
        # we set use-only-tar-bz2 to false in order for conda to properly find new packages to be installed
        # for more info see https://github.com/conda-incubator/setup-miniconda/issues/264
        use-only-tar-bz2: false
    - shell: bash -l {0}
      run: |
        conda run -n ${{ inputs.activate-environment }} pip install .
        conda list -n ${{ inputs.activate-environment }}
