FROM modin-project/modin-base

ARG ENVIRONMENT=environment.yml

ADD modin.tar /modin
ADD git-rev /modin/git-rev

WORKDIR /modin

RUN conda env create -f environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "modin", "/bin/bash", "-c"]

RUN conda list

RUN echo "source activate modin" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH
