channels:
  - conda-forge
dependencies:
  - python=3.6
  - pandas
  - numpy>=1.18.5
  - pyarrow>=4.0.1
  - dask[complete]>=2.22.0,<2021.3.0
  - distributed>=2.22.0,<2021.3.0
  - pickle5 # for dask to correctly serialize nested functions
  - fsspec
  - xarray
  - Jinja2
  - scipy
  - pip
  - s3fs>=2021.8,<=2022.1.0
  - feather-format
  - lxml
  - openpyxl
  - xlrd
  - matplotlib<=3.2.2
  - sqlalchemy>=1.4.0
  - pandas-gbq
  - pytables
  - msgpack-python
  - psutil
  - pytest>=6.0.1
  - pytest-benchmark
  - pytest-cov>=2.10.1
  - pytest-xdist>=2.1.0
  - packaging
  - coverage<5.0
  - pygithub==1.53
  - rpyc==4.1.5
  - cloudpickle
  - boto3
  - scikit-learn
  - pymssql
  - psycopg2
  - jupyter>=1.0.0 # modin-spreadsheet needs that, but it won't install on Windows on Py36 via pip
  - pip:
      - modin-spreadsheet>=0.1.1
      - tqdm
      - ray[default]>=1.4.0
      # TODO: remove when resolving GH#4398
      - redis>=3.5.0,<4.0.0
      - black
      # TODO: remove when flake8 5.x stabilizes and appears in both pip and conda-forge; see GH-#4745
      - flake8<5
      # The `numpydoc` version should match the version installed in the `lint-pydocstyle` job of the CI.
      - numpydoc==1.1.0
