#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

set -e

printf "running flake8. This script will preempt the commit if flake8 fails.\n"
flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py
printf "flake8 passed!\n"

printf "pre-commit hook finished!\n"
