name: io-ci
on: pull_request
jobs:
  test-io:
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8"]
        engine: ["python", "ray", "dask"]
        exclude:
          - os: windows-latest
            engine: "python"
    env:
      MODIN_ENGINE: ${{matrix.engine}}
      MODIN_MEMORY: 1000000000
    name: test-io (os ${{matrix.os}}, engine ${{matrix.engine}}, python ${{matrix.python-version}})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin
          environment-file: environment-dev.yml
          python-version: ${{matrix.python-version}}
          channel-priority: strict
      - name: Conda environment
        run: |
          conda info
          conda list
      - name: Install HDF5
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libhdf5-dev
      - timeout-minutes: 30
        run: python -m pytest modin/pandas/test/test_io.py --verbose
      - if: matrix.os == 'ubuntu-latest'
        run: |
          curl -o codecov https://codecov.io/bash
          VERSION=$(grep -o 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
          curl -o SHA512SUM "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA512SUM"
          if sha512sum -c --ignore-missing --status SHA512SUM; then
              bash ./codecov
          else
              echo 'CORRUPTED CODECOV SCRIPT!!!'
              exit 10
          fi
      - if: matrix.os == 'windows-latest'
        run: |
          choco install codecov
          codecov -f ./coverage.xml
